Repository qfsae/pcb, pull requests merged in 2020-12, with the labels that each got.

#20 Add Link to a Git Reference Page
  README.md
Labels: documentation

#17 DevKit PCB
  DevKit/DevKit.PcbDoc
  DevKit/DevKit.PrjPcb
  DevKit/DevKit.PrjPcbStructure
  DevKit/Header.PcbLib
  DevKit/Header.SchLib
  DevKit/OUTPUT.OutJob
  DevKit/TOP.SchDoc
  DevKit/arduino_uno_drawing_5000x3515.png
  DevKit/credit.md.txt
  DevKit/gerbers/2020-12-04-macro.APR_LIB
  DevKit/gerbers/2020-12-04.1
  DevKit/gerbers/2020-12-04.DRR
  DevKit/gerbers/2020-12-04.EXTREP
  DevKit/gerbers/2020-12-04.GBL
  DevKit/gerbers/2020-12-04.GBO
  DevKit/gerbers/2020-12-04.GBP
  DevKit/gerbers/2020-12-04.GBS
  DevKit/gerbers/2020-12-04.GKO
  DevKit/gerbers/2020-12-04.GM1
  DevKit/gerbers/2020-12-04.GM13
  DevKit/gerbers/2020-12-04.GM15
  DevKit/gerbers/2020-12-04.GM16
  DevKit/gerbers/2020-12-04.GM2
  DevKit/gerbers/2020-12-04.GM20
  DevKit/gerbers/2020-12-04.GM21
  DevKit/gerbers/2020-12-04.GM23
  DevKit/gerbers/2020-12-04.GM24
  DevKit/gerbers/2020-12-04.GM3
  DevKit/gerbers/2020-12-04.GM5
  DevKit/gerbers/2020-12-04.GML
  DevKit/gerbers/2020-12-04.GPB
  DevKit/gerbers/2020-12-04.GPT
  DevKit/gerbers/2020-12-04.GTL
  DevKit/gerbers/2020-12-04.GTO
  DevKit/gerbers/2020-12-04.GTP
  DevKit/gerbers/2020-12-04.GTS
  DevKit/gerbers/2020-12-04.LDP
  DevKit/gerbers/2020-12-04.REP
  DevKit/gerbers/2020-12-04.RUL
  DevKit/gerbers/2020-12-04.TXT
  DevKit/gerbers/2020-12-04.apr
  DevKit/gerbers/Status Report.Txt
  DevKit/schematics/schematic.PDF
Labels: PCB, WIP

#18 CAN shield Marty Fay
  onboarding/Q21/CAN-shield-MF/MartyCANshield.PrjPcb
  onboarding/Q21/CAN-shield-MF/OUTPUT.OutJob
  onboarding/Q21/CAN-shield-MF/PCB.PcbDoc
  onboarding/Q21/CAN-shield-MF/TOP.SchDoc
  onboarding/Q21/CAN-shield-MF/template.PrjPcbStructure
  onboarding/Q21/README.md
Labels: PCB

#25 Transceiver Capacitor Fix
  Transceiver/OUTPUT.OutJob
  Transceiver/Transceiver.PcbDoc
  Transceiver/Transceiver.PrjPcb
  Transceiver/Transceiver.SchDoc
  Transceiver/gerbers/BOM.xls
  Transceiver/gerbers/Pick Place for Transceiver.csv
  Transceiver/gerbers/Status Report.Txt
  Transceiver/gerbers/Transceiver-macro.APR_LIB
  Transceiver/gerbers/Transceiver.1
  Transceiver/gerbers/Transceiver.DRR
  Transceiver/gerbers/Transceiver.EXTREP
  Transceiver/gerbers/Transceiver.GBL
  Transceiver/gerbers/Transceiver.GBO
  Transceiver/gerbers/Transceiver.GBP
  Transceiver/gerbers/Transceiver.GBS
  Transceiver/gerbers/Transceiver.GD1
  Transceiver/gerbers/Transceiver.GG1
  Transceiver/gerbers/Transceiver.GKO
  Transceiver/gerbers/Transceiver.GM1
  Transceiver/gerbers/Transceiver.GM13
  Transceiver/gerbers/Transceiver.GML
  Transceiver/gerbers/Transceiver.GPB
  Transceiver/gerbers/Transceiver.GPT
  Transceiver/gerbers/Transceiver.GTL
  Transceiver/gerbers/Transceiver.GTO
  Transceiver/gerbers/Transceiver.GTP
  Transceiver/gerbers/Transceiver.GTS
  Transceiver/gerbers/Transceiver.LDP
  Transceiver/gerbers/Transceiver.REP
  Transceiver/gerbers/Transceiver.RUL
  Transceiver/gerbers/Transceiver.TXT
  Transceiver/gerbers/Transceiver.apr
Labels: enhancement

#26 Add JLC PCB Design Rules to Arduino Shield Template Project
  reference/UNOR3Shield_Blank/ArduinoUnoShield.PcbDoc
  reference/UNOR3Shield_Blank/ArduinoUnoShield.PrjPcb
  reference/UNOR3Shield_Blank/OUTPUT.OutJob
Labels: bug

#29 Update .gitignore
  .gitignore
  template/OUTPUT.OutJob
Labels: enhancement

#30 Add QFSAE logo to the PCB template
  template/PCB.PcbDoc
  template/TOP.SchDoc
Labels: enhancement
